[versions]
android-gradle = "7.4.1"
androidx-activity = "1.6.1"
androidx-compose-compiler = "1.4.0"
androidx-compose-bom = "2023.01.00"
accompanist-navigation = "0.28.0"
androidx-lifecycle = "2.5.1"
kotlinx-coroutines = "1.6.4"
coil = "2.2.2"
junit = "1.1.5"
koin = "3.3.2"
kotlin = "1.8.0"
mockk = "1.13.3"
okhttp3 = "4.10.0"
retrofit = "2.9.0"

[libraries]
android-tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-arch-core-testing = "androidx.arch.core:core-testing:2.1.0"
androidx-test-core = "androidx.test:core:1.5.0"

kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
kotlinx-collections-immutable = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.5"
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist-navigation" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-uiTest-junit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-uiTest-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"

androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

mockk-library = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

squareup-okhttp3-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
squareup-retrofit-library = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-converter-kotlinxSerialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"

[plugins]
kotlinx-serializationPlugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
